apiVersion: batch/v1
kind: Job
metadata:
  name: autognuchess
spec:
  template:
    spec:
      containers:
        - name: autognuchess 
          image: schnitz81/autognuchess
          args: ["30"]
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 1
