apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: corebench
  name: corebench
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: corebench
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: corebench
    spec:
      containers:
      - image: schnitz81/corebench
        imagePullPolicy: Always
        name: corebench
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

