apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}-pvc
  namespace: {{ .Values.deployment.namespace }}
  annotations: {}
spec:
  accessModes:
{{ toYaml .Values.pvc.accessModes | indent 4 }}
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvc.name }}-pv
spec:
  capacity:
    storage: "{{ .Values.pvc.size }}"
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  hostPath:
    path: {{ .Values.container.mountpath }}
  nodeAffinity:
{{ toYaml .Values.pvc.nodeAffinity | indent 4 }}
