apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example-pvc
  namespace: default
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
